name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Xcode version
        run: xcodebuild -version
      - name: Build
        run: xcodebuild -project Whisky.xcodeproj -scheme Whisky -configuration Debug CODE_SIGNING_ALLOWED=NO SWIFTLINT_SKIP=YES build
